### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by benmoran56** [codyd51/flaccid#1]
Hello, could you confirm which license this code is under? Thanks!

**Comment by codyd51** [comment]
Hi! This code is under the MIT license. I have added a readme with this notice. I am curious what you end up using it for, though :-) 
 
Thanks for reaching out to ask!

**Comment by benmoran56** [comment]
Thanks a lot! 

I'm a contributor to the [pyglet](http://www.pyglet.org) project, and I'm exploring the possibility of adding support for at least one compressed audio format without dependencies. We only have built-in support for wav at the moment.

This support does not have to be real-time,  but in the past I have mocked up an example for FLAC that was able to decode in real-time. If split up across a few cores, it was able to do about 1minute of audio in about 10 seconds. This should be adequate. 

I don't know that I can use your code directly, but I was interested in some of your methods and classes to save time.
